language: node_js
node_js: stable
git:
    submodules: false
    
cache:
  directories:
  - node_modules

before_install:
- git submodule update --init --recursive

install:
- npm install
- npm install -g gulp
- npm install grunt-cli -g
- cd themes/tranquilpeak
- npm install 
- bower install
- grunt buildProd

before_script:
- cd ../..

script:
- gulp build

after_script:
- cd public
- git init
- git config user.name "James Yang"
- git config user.email "jawa.yang@gmail.com"
- git add .
- git commit -m "Update Daily"
- git push --force --quiet "https://${GH_TOKEN}@${GIT_PAGE_REF}" master:master

branches:
  only:
  - develop

env:
  global:
  - GIT_PAGE_REF: github.com/jawayang/Daily.git
  - secure: BHeiFDdajTKaweSyXstpc8BBbLwyTGO8VfxFuqturKyRe42LLtLgLQWNoFi5xqFEkm0s88FqKpA8ERCgVhoeZplQOL2UqMeMb6PMocGseAy4C4McpzYPyaW+13XJIU3CzI0j57uGipt7UwRXNqnZ/cESPmLuOkYMrDS9vRlBxiI9uqMo4so5Z6nIyz3XWcd/BHu2/3J+FoZ99LoCcLQZJ04E+0KtN/B7f5Le3vMjr2Y4t9x/Bs+1QyoAxFaQIggvHw2DK+bHhbIukkDqnR1CDD2ZWc9yC+D8oIMDSTF+EzICp2aFHVouN5k6akvWzs267Q4f6xQzIHs/lhSf6Zp+na3QGWxdsMZPF37lxXAvsGRypdQUpLRfbF6996U3EfdXkEDs7H0cuthAbbR/quutia+9xTFZfGoUw4lYdsZBjmqmN+WPDZIA0vM/96wMeD5XamsU+1n2RZiFNM1IRQUqFJbcnjD67I7b7F+RyBrImZ0+bVqZWrb3myqs8A6B75aN2oJXzO5zsbjquHAezahw0LwR4Y8ZRqdE9jT9yRixoIMqRKzLL/sAv+Ba2B/3q0GVPMPuDX8wwdfbgD8lQhatwyb+Pfju3JrSzF/OTKr8bbN+BOV17d9ENtAHJDIfKNm6E6BzBvNww0iMNckbmH50Zipyu6KR8zK3KTn8IbB7nlc=

notifications:
  email: false
  # - jawa.yang@gmail.com
  # on_success: change
  # on_failure: always